# Generated by Django 2.0.13 on 2023-01-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('releasedate', models.CharField(max_length=15, verbose_name='개봉년도')),
                ('genre', models.CharField(max_length=20, verbose_name='장르')),
                ('score', models.CharField(max_length=15, verbose_name='별점')),
                ('runtime', models.CharField(max_length=15, verbose_name='러닝타임')),
                ('review', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('cast', models.CharField(max_length=200, verbose_name='배우')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
